CREATE TABLE "accounts_administrator" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "notes" text NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_apiactionlog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "actor_role" varchar(20) NOT NULL, "method" varchar(10) NOT NULL, "path" varchar(255) NOT NULL, "endpoint" varchar(120) NOT NULL, "action" varchar(120) NOT NULL, "success" bool NOT NULL, "status_code" smallint unsigned NULL CHECK ("status_code" >= 0), "before_data" text NOT NULL CHECK ((JSON_VALID("before_data") OR "before_data" IS NULL)), "after_data" text NOT NULL CHECK ((JSON_VALID("after_data") OR "after_data" IS NULL)), "meta" text NOT NULL CHECK ((JSON_VALID("meta") OR "meta" IS NULL)), "created_at" datetime NOT NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_applicant" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "patronymic" varchar(150) NOT NULL, "telegram" varchar(100) NOT NULL, "consent_email" bool NOT NULL, "consent_telegram" bool NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "telegram_chat_id" bigint NULL, "telegram_start_token" varchar(64) NULL UNIQUE, "birth_date" date NULL, "citizenship" varchar(2) NOT NULL, "city" varchar(150) NOT NULL, "gender" varchar(1) NOT NULL, "phone" varchar(30) NOT NULL, "skills" text NOT NULL CHECK ((JSON_VALID("skills") OR "skills" IS NULL)), "address" varchar(500) NOT NULL, "location_type" varchar(10) NOT NULL, "metro_city_id" varchar(10) NOT NULL, "metro_line_color" varchar(7) NOT NULL, "metro_line_name" varchar(150) NOT NULL, "metro_station_id" varchar(20) NOT NULL, "metro_station_name" varchar(150) NOT NULL, "salary_expectation_from" integer NULL, "salary_expectation_to" integer NULL, "avatar" varchar(100) NULL, "about_me" text NOT NULL, "desired_position" varchar(255) NOT NULL, "github_url" varchar(300) NOT NULL, "portfolio_url" varchar(300) NOT NULL, "was_manager" bool NOT NULL, "manager_company_logo" varchar(500) NOT NULL, "resume_file" varchar(100) NULL, "metro_stations" text NOT NULL CHECK ((JSON_VALID("metro_stations") OR "metro_stations" IS NULL)));

CREATE TABLE "accounts_application" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cover_letter" text NOT NULL, "status" varchar(16) NOT NULL, "created_at" datetime NOT NULL, "applicant_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "vacancy_id" bigint NOT NULL REFERENCES "vacancies_vacancy" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_calendarnote" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "created_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "note_time" time NULL, "reminded" bool NOT NULL, "color" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "text" text NOT NULL);

CREATE TABLE "accounts_chat" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "applicant_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "manager_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "deleted_by_applicant" bool NOT NULL, "deleted_by_manager" bool NOT NULL);

CREATE TABLE "accounts_education" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "level" varchar(30) NOT NULL, "institution" varchar(255) NOT NULL, "graduation_year" integer NULL, "faculty" varchar(255) NOT NULL, "specialization" varchar(255) NOT NULL, "order" smallint unsigned NOT NULL CHECK ("order" >= 0), "applicant_id" bigint NOT NULL REFERENCES "accounts_applicant" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_extraeducation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NOT NULL, "order" smallint unsigned NOT NULL CHECK ("order" >= 0), "applicant_id" bigint NOT NULL REFERENCES "accounts_applicant" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_filterpreset" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "filters" text NOT NULL CHECK ((JSON_VALID("filters") OR "filters" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_interview" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "scheduled_at" datetime NOT NULL, "location" varchar(500) NOT NULL, "notes" text NOT NULL, "status" varchar(16) NOT NULL, "created_at" datetime NOT NULL, "applicant_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "manager_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "vacancy_id" bigint NULL REFERENCES "vacancies_vacancy" ("id") DEFERRABLE INITIALLY DEFERRED, "reminded_1d" bool NOT NULL, "reminded_1h" bool NOT NULL, "reminded_now" bool NOT NULL);

CREATE TABLE "accounts_manager" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "patronymic" varchar(150) NOT NULL, "company" varchar(255) NOT NULL, "phone" varchar(30) NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "telegram" varchar(100) NOT NULL, "consent_email" bool NOT NULL, "consent_telegram" bool NOT NULL, "telegram_chat_id" bigint NULL, "avatar" varchar(100) NULL, "company_logo" varchar(100) NULL);

CREATE TABLE "accounts_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "created_at" datetime NOT NULL, "is_read" bool NOT NULL, "chat_id" bigint NOT NULL REFERENCES "accounts_chat" ("id") DEFERRABLE INITIALLY DEFERRED, "sender_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "file" varchar(100) NULL);

CREATE TABLE "accounts_useruipreference" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "theme" varchar(10) NOT NULL, "updated_at" datetime NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "accounts_workexperience" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "company" varchar(255) NOT NULL, "position" varchar(255) NOT NULL, "start_month" integer NULL, "start_year" integer NULL, "end_month" integer NULL, "end_year" integer NULL, "is_current" bool NOT NULL, "responsibilities" text NOT NULL, "order" smallint unsigned NOT NULL CHECK ("order" >= 0), "applicant_id" bigint NOT NULL REFERENCES "accounts_applicant" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "vacancies_bookmark" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "vacancy_id" bigint NOT NULL REFERENCES "vacancies_vacancy" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "vacancies_employer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hh_id" varchar(64) NULL UNIQUE, "name" varchar(255) NOT NULL, "logo_url" varchar(200) NOT NULL, "raw" text NOT NULL CHECK ((JSON_VALID("raw") OR "raw" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "hh_rating" real NULL, "rating_raw" varchar(128) NOT NULL, "rating_updated_at" datetime NULL, "dreamjob_rating" real NULL, "dreamjob_rating_raw" varchar(128) NOT NULL, "dreamjob_rating_updated_at" datetime NULL);

CREATE TABLE "vacancies_hharea" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "area_id" varchar(32) NOT NULL UNIQUE, "name" varchar(255) NOT NULL, "parent_id" varchar(32) NOT NULL, "raw_json" text NOT NULL CHECK ((JSON_VALID("raw_json") OR "raw_json" IS NULL)), "updated_at" datetime NOT NULL);

CREATE TABLE "vacancies_hhdictionaryitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dictionary" varchar(64) NOT NULL, "item_id" varchar(64) NOT NULL, "name" varchar(255) NOT NULL, "parent_id" varchar(64) NOT NULL, "raw_json" text NOT NULL CHECK ((JSON_VALID("raw_json") OR "raw_json" IS NULL)), "updated_at" datetime NOT NULL);

CREATE TABLE "vacancies_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "author" varchar(128) NOT NULL, "text" text NOT NULL, "created_at" datetime NOT NULL, "vacancy_id" bigint NOT NULL REFERENCES "vacancies_vacancy" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "vacancies_vacancy" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "external_id" varchar(64) NOT NULL, "title" varchar(255) NOT NULL, "company" varchar(255) NOT NULL, "country" varchar(128) NOT NULL, "region" varchar(128) NOT NULL, "is_remote" bool NOT NULL, "url" varchar(500) NOT NULL, "published_at" datetime NOT NULL, "raw_json" text NOT NULL CHECK ((JSON_VALID("raw_json") OR "raw_json" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "work_format" varchar(16) NOT NULL, "is_hybrid" bool NOT NULL, "is_onsite" bool NOT NULL, "experience_id" varchar(32) NOT NULL, "experience_name" varchar(128) NOT NULL, "key_skills_text" text NOT NULL, "salary_currency" varchar(16) NOT NULL, "salary_from" integer NULL, "salary_to" integer NULL, "employer_id" bigint NULL REFERENCES "vacancies_employer" ("id") DEFERRABLE INITIALLY DEFERRED, "accept_incomplete_resumes" bool NOT NULL, "accept_kids" bool NOT NULL, "accept_temporary" bool NOT NULL, "employment_form_id" varchar(32) NOT NULL, "employment_form_name" varchar(128) NOT NULL, "employment_id" varchar(32) NOT NULL, "employment_name" varchar(128) NOT NULL, "is_internship" bool NOT NULL, "schedule_id" varchar(32) NOT NULL, "schedule_name" varchar(128) NOT NULL, "branded_description" text NOT NULL, "description" text NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "is_active" bool NOT NULL, "address_comment" varchar(255) NOT NULL, "benefits_text" text NOT NULL, "contact_phone" varchar(30) NOT NULL, "contract_gpc" bool NOT NULL, "contract_labor" bool NOT NULL, "employee_type" varchar(16) NOT NULL, "has_night_shifts" bool NOT NULL, "hide_address" bool NOT NULL, "hours_per_day" varchar(8) NOT NULL, "lat" real NULL, "lon" real NULL, "metro_line_color" varchar(16) NOT NULL, "metro_line_name" varchar(128) NOT NULL, "metro_station_name" varchar(128) NOT NULL, "payment_frequency" varchar(16) NOT NULL, "requirements_text" text NOT NULL, "salary_gross" bool NOT NULL, "salary_period" varchar(16) NOT NULL, "work_address" varchar(500) NOT NULL, "work_schedule" varchar(32) NOT NULL, "working_conditions_text" text NOT NULL, "metro_city_id" varchar(10) NOT NULL);

CREATE TABLE "vacancies_vacancyview" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "viewed_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "vacancy_id" bigint NOT NULL REFERENCES "vacancies_vacancy" ("id") DEFERRABLE INITIALLY DEFERRED);

