# Generated by Django 6.0.2 on 2026-02-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('consent_email', models.BooleanField(default=False, verbose_name='Согласие на e-mail')),
                ('consent_telegram', models.BooleanField(default=False, verbose_name='Согласие на Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
