# Generated by Django 6.0.2 on 2026-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicant_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='telegram_start_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telegram start token'),
        ),
    ]
