# Generated by Django 6.0.2 on 2026-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
