# Generated by Django 6.0.2 on 2026-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manager_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('RU', 'Россия'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Киргизия'), ('AM', 'Армения'), ('TJ', 'Таджикистан'), ('UZ', 'Узбекистан'), ('UA', 'Украина'), ('MD', 'Молдова'), ('AZ', 'Азербайджан'), ('TM', 'Туркменистан')], max_length=2, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
    ]
