# Generated by Django 6.0.2 on 2026-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_applicant_skills_education_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location_type',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Тип местоположения'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro_city_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID города метро (HH)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro_line_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет линии HEX'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro_line_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название линии'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro_station_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID станции метро (HH)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro_station_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название станции'),
        ),
    ]
