# Generated by Django 6.0.2 on 2026-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by_applicant',
            field=models.BooleanField(default=False, verbose_name='Удалён соискателем'),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_manager',
            field=models.BooleanField(default=False, verbose_name='Удалён менеджером'),
        ),
    ]
