# Generated by Django 6.0.2 on 2026-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chat_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='consent_email',
            field=models.BooleanField(default=False, verbose_name='Согласие на e-mail'),
        ),
        migrations.AddField(
            model_name='manager',
            name='consent_telegram',
            field=models.BooleanField(default=False, verbose_name='Согласие на Telegram'),
        ),
        migrations.AddField(
            model_name='manager',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat id'),
        ),
    ]
