# Generated by Django 6.0.2 on 2026-03-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message_file_attachment'),
        ('vacancies', '0016_add_description_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='salary_expectation_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата от (ожидаемая)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='salary_expectation_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата до (ожидаемая)'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('viewed', 'Просмотрено'), ('accepted', 'Приглашение'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
                'unique_together': {('vacancy', 'applicant')},
            },
        ),
    ]
