# Generated by Django 6.0.2 on 2026-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_salary_and_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='manager',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/%Y/', verbose_name='Логотип компании'),
        ),
    ]
