# Generated by Django 6.0.2 on 2026-03-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_avatar_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('filters', models.JSONField(default=dict, verbose_name='Фильтры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пресет фильтров',
                'verbose_name_plural': 'Пресеты фильтров',
                'ordering': ['name'],
            },
        ),
    ]
