# Generated by Django 6.0.2 on 2026-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_filter_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='desired_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='github_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Портфолио / сайт'),
        ),
    ]
