# Generated by Django 6.0.2 on 2026-03-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='was_manager',
            field=models.BooleanField(default=False, verbose_name='Был менеджером'),
        ),
    ]
