# Generated by Django 6.0.2 on 2026-03-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_calendar_note'),
        ('vacancies', '0019_add_bookmark_vacancyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Место / ссылка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('cancelled', 'Отменено'), ('done', 'Завершено')], default='scheduled', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_applicant', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_manager', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
