# Generated by Django 6.0.2 on 2026-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_calendarnote_reminded'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarnote',
            name='color',
            field=models.CharField(blank=True, default='#c2a35a', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='calendarnote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст заметки'),
        ),
    ]
