# Generated by Django 6.0.2 on 2026-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_calendarnote_title_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='manager_company_logo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Путь к логотипу компании'),
        ),
    ]
