# Generated by Django 6.0.2 on 2026-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_manager_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/', verbose_name='Файл резюме (Word)'),
        ),
    ]
