# Generated by Django 6.0.2 on 2026-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_extra_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='metro_stations',
            field=models.JSONField(blank=True, default=list, verbose_name='Список станций метро'),
        ),
        migrations.AlterField(
            model_name='extraeducation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
