# Generated by Django 4.2.29 on 2026-04-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_alter_apiactionlog_actor_role_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('suggestion', 'Предложение'), ('criticism', 'Критика')], default='suggestion', max_length=16)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение/критика пользователя',
                'verbose_name_plural': 'Предложения и критика пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
