# Generated by Django 4.2.29 on 2026-04-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0032_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedback_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('active', 'В ленте'), ('archived', 'В архиве'), ('resolved', 'Реализовано'), ('rejected', 'Отклонено')], db_index=True, default='active', max_length=16),
        ),
    ]
