# Generated by Django 4.2.29 on 2026-04-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0033_userfeedback_processed_at_userfeedback_processed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport_rf', 'Паспорт РФ'), ('snils', 'СНИЛС'), ('inn', 'ИНН'), ('foreign_passport', 'Загранпаспорт'), ('driver_license', 'Водительское удостоверение'), ('military_id', 'Военный билет')], db_index=True, max_length=32, verbose_name='Тип документа')),
                ('serial', models.CharField(blank=True, max_length=32, verbose_name='Серия')),
                ('number', models.CharField(max_length=32, verbose_name='Номер')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('division_code', models.CharField(blank=True, max_length=16, verbose_name='Код подразделения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ пользователя',
                'verbose_name_plural': 'Документы пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.userdocument')),
            ],
            options={
                'verbose_name': 'Файл документа пользователя',
                'verbose_name_plural': 'Файлы документов пользователей',
                'ordering': ['created_at'],
            },
        ),
    ]
