# Generated by Django 4.2.29 on 2026-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userdocument_userdocumentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraeducation',
            name='document_serial',
            field=models.CharField(blank=True, max_length=120, verbose_name='Серийный номер документа'),
        ),
    ]
