# Generated by Django 4.2.29 on 2026-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_extraeducation_document_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатели'},
        ),
    ]
