# Generated by Django 4.2.29 on 2026-04-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0036_alter_applicant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiactionlog',
            name='action',
            field=models.CharField(max_length=120, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='actor_role',
            field=models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('manager', 'Manager'), ('applicant', 'Applicant'), ('user', 'User')], default='system', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='after_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='После изменения'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='before_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='До изменения'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=120, verbose_name='Эндпоинт'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='method',
            field=models.CharField(max_length=10, verbose_name='HTTP-метод'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='apiactionlog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telegram',
            field=models.CharField(max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telegram_start_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Стартовый токен Telegram'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
