# Generated by Django 4.2.29 on 2026-04-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_apiactionlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiactionlog',
            name='actor_role',
            field=models.CharField(choices=[('system', 'Система'), ('admin', 'Администратор'), ('moderator', 'Модератор'), ('manager', 'Менеджер'), ('applicant', 'Соискатель'), ('user', 'Пользователь')], default='system', max_length=20, verbose_name='Роль'),
        ),
    ]
