"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (if present); silently ignored in production.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5anve2ez#=k4xki7oaqx%2cc=%@(rw^i(t)qxsf4_9o@hjze9g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Base URL used in outgoing notifications (email, Telegram).
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
HH_API_USER_AGENT = os.environ.get('HH_API_USER_AGENT', f'job-aggregator-diploma/1.0 (+{SITE_URL})')
HH_API_TOKEN = os.environ.get('HH_API_TOKEN', '').strip()
HH_API_CLIENT_ID = os.environ.get('HH_API_CLIENT_ID', '').strip()
HH_API_CLIENT_SECRET = os.environ.get('HH_API_CLIENT_SECRET', '').strip()
HH_SYNC_INTERVAL_SEC = int(os.environ.get('HH_SYNC_INTERVAL_SEC', '300'))
HH_FETCH_PAGES = int(os.environ.get('HH_FETCH_PAGES', '5'))
HH_FETCH_PER_PAGE = int(os.environ.get('HH_FETCH_PER_PAGE', '100'))
HH_STARTUP_FETCH_PAGES = int(os.environ.get('HH_STARTUP_FETCH_PAGES', '1'))
HH_STARTUP_FETCH_PER_PAGE = int(os.environ.get('HH_STARTUP_FETCH_PER_PAGE', '10'))
VACANCY_FETCH_ON_STARTUP = os.environ.get('VACANCY_FETCH_ON_STARTUP', 'false').lower() in (
    '1', 'true', 'yes', 'on',
)
HH_BACKFILL_LIMIT = int(os.environ.get('HH_BACKFILL_LIMIT', '80'))
HH_STALE_CHECK_INTERVAL_SEC = int(os.environ.get('HH_STALE_CHECK_INTERVAL_SEC', '21600'))
HH_STALE_CHECK_BATCH = int(os.environ.get('HH_STALE_CHECK_BATCH', '50'))

# ── Media files (user uploads) ───────────────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'vacancies',
    'accounts',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Session': {
            'type': 'apiKey',
            'name': 'sessionid',
            'in': 'cookie',
        }
    },
    'USE_SESSION_AUTH': True,
    'LOGIN_URL': '/accounts/login/',
    'LOGOUT_URL': '/accounts/logout/',
    'DEFAULT_INFO': 'config.urls.api_info',
    'DEFAULT_GENERATOR_CLASS': 'config.openapi_generator.RussianOpenAPISchemaGenerator',
}

# Документация ReDoc (тот же OpenAPI, что и у Swagger)
REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': 'all',
    'PATH_IN_MIDDLE': False,
    'NATIVE_SCROLLBARS': False,
    'REQUIRED_PROPS_FIRST': True,
    'HIDE_DOWNLOAD_BUTTON': False,
    'FETCH_SCHEMA_WITH_QUERY': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.service_status.service_status_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            # init_command убираем — это MySQL-опция, не SQLite
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# reload trigger

# Celery configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_POOL = 'threads'   # solo breaks on Windows with >1 concurrent task
CELERY_WORKER_CONCURRENCY = 4    # 4 threads — good for I/O-bound HTTP fetches
# Enable Redis priority queues (0=lowest … 9=highest).
# User-triggered description fetches use priority=9; backfill uses priority=1.
CELERY_TASK_QUEUE_MAX_PRIORITY = 10
CELERY_TASK_DEFAULT_PRIORITY = 5

FALLBACK_TRUDVSEM_ENABLED = os.environ.get('FALLBACK_TRUDVSEM_ENABLED', 'true').lower() in (
    '1', 'true', 'yes', 'on',
)
FALLBACK_TRUDVSEM_LIMIT = int(os.environ.get('FALLBACK_TRUDVSEM_LIMIT', '200'))
FALLBACK_TRUDVSEM_STARTUP_LIMIT = int(os.environ.get('FALLBACK_TRUDVSEM_STARTUP_LIMIT', '10'))
FALLBACK_TRUDVSEM_SYNC_INTERVAL_SEC = int(
    os.environ.get('FALLBACK_TRUDVSEM_SYNC_INTERVAL_SEC', str(HH_SYNC_INTERVAL_SEC))
)
FALLBACK_TRUDVSEM_TTL_DAYS = int(os.environ.get('FALLBACK_TRUDVSEM_TTL_DAYS', '5'))
FALLBACK_TRUDVSEM_STATUS_CHECK_INTERVAL_SEC = int(
    os.environ.get('FALLBACK_TRUDVSEM_STATUS_CHECK_INTERVAL_SEC', '3600')
)
FALLBACK_TRUDVSEM_STATUS_CHECK_BATCH = int(
    os.environ.get('FALLBACK_TRUDVSEM_STATUS_CHECK_BATCH', '100')
)
FALLBACK_TRUDVSEM_RECENT_MINUTES = int(os.environ.get('FALLBACK_TRUDVSEM_RECENT_MINUTES', '5'))
FALLBACK_TRUDVSEM_MAX_PAGES_PER_RUN = int(os.environ.get('FALLBACK_TRUDVSEM_MAX_PAGES_PER_RUN', '1000'))
FALLBACK_TRUDVSEM_TEXTS = os.environ.get(
    'FALLBACK_TRUDVSEM_TEXTS',
    'продавец,кассир,водитель,бухгалтер,менеджер,администратор,python,аналитик,разработчик',
)

# 2GIS API key (can be overridden via environment variable)
DGIS_API_KEY = os.environ.get('DGIS_API_KEY', '0cd687b3-98c4-463e-9f30-cf4bd2dc4c4e')

# ── Database backups ──────────────────────────────────────────────────────────
BACKUP_DIR = BASE_DIR / 'backups'
DB_BACKUP_MAX_COUNT = 3  # keep at most this many backups; oldest is deleted when exceeded
CELERY_STATUS_TTL_SECONDS = 90

# Telegram bot token used to send welcome messages to users who consent.
# For production, override via environment variable `TELEGRAM_BOT_TOKEN`.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '8503249417:AAGWJdHqYCpki4TDZEhbegecGYVbVIXLHQY')
# Celery beat schedule can be set in config/celery.py; default fetch every 10 minutes

# ── Email settings ──────────────────────────────────────────────────────────
# Configure credentials in .env (see .env.example).  Port 587 + STARTTLS works
# for Mail.ru, Gmail, Yandex and most other providers.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST     = os.environ.get('EMAIL_HOST',    'smtp.mail.ru')
EMAIL_PORT     = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS  = os.environ.get('EMAIL_USE_TLS',  'True') != 'False'
EMAIL_USE_SSL  = False   # TLS (STARTTLS) and SSL are mutually exclusive
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER',     '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL',  'JobFlex <noreply@jobflex.ru>')
