# Generated by Django 6.0.2 on 2026-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('is_remote', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at',),
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
