# Generated by Django 6.0.2 on 2026-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('remote', 'Удалённо'), ('hybrid', 'Гибрид'), ('onsite', 'На месте')], default='onsite', max_length=16),
        ),
    ]
