# Generated by Django 6.0.2 on 2026-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_work_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_onsite',
            field=models.BooleanField(default=True),
        ),
    ]
