# Generated by Django 6.0.2 on 2026-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_is_hybrid_vacancy_is_onsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HhArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=32)),
                ('raw_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HhDictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.CharField(max_length=64)),
                ('item_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=64)),
                ('raw_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('dictionary', 'name'),
                'unique_together': {('dictionary', 'item_id')},
            },
        ),
    ]
