# Generated by Django 6.0.2 on 2026-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_hharea_hhdictionaryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
