# Generated by Django 6.0.2 on 2026-02-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_experience_id_vacancy_experience_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('external_id',)},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='source',
        ),
    ]
