# Generated by Django 6.0.2 on 2026-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_unique_together_remove_vacancy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='key_skills_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
