# Generated by Django 6.0.2 on 2026-02-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_key_skills_text_vacancy_salary_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_sources', models.JSONField(blank=True, default=dict)),
                ('rating_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-primary_rating', 'name'),
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.employer'),
        ),
    ]
