# Generated by Django 6.0.2 on 2026-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_remove_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='hh_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='rating_raw',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='employer',
            name='rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
