# Generated by Django 6.0.2 on 2026-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_add_dreamjob_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='accept_incomplete_resumes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='accept_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='accept_temporary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_form_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_form_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_internship',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
