# Generated by Django 6.0.2 on 2026-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_add_schedule_employment_label_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='branded_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
