# Generated by Django 6.0.2 on 2026-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_add_created_by_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к адресу'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='benefits_text',
            field=models.TextField(blank=True, verbose_name='Льготы и преимущества'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contract_gpc',
            field=models.BooleanField(default=False, verbose_name='Договор ГПХ'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contract_labor',
            field=models.BooleanField(default=False, verbose_name='Трудовой договор'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_type',
            field=models.CharField(blank=True, max_length=16, verbose_name='Тип сотрудника'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='has_night_shifts',
            field=models.BooleanField(default=False, verbose_name='Ночные смены'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hide_address',
            field=models.BooleanField(default=False, verbose_name='Скрыть адрес'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hours_per_day',
            field=models.CharField(blank=True, max_length=8, verbose_name='Часов в день'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='metro_line_color',
            field=models.CharField(blank=True, max_length=16, verbose_name='Цвет линии метро'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='metro_line_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Линия метро'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='metro_station_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Станция метро'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='payment_frequency',
            field=models.CharField(blank=True, max_length=16, verbose_name='Частота выплат'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_text',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_gross',
            field=models.BooleanField(default=True, verbose_name='До вычета налогов'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_period',
            field=models.CharField(blank=True, max_length=16, verbose_name='Период зарплаты'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=32, verbose_name='График'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_conditions_text',
            field=models.TextField(blank=True, verbose_name='Условия работы'),
        ),
    ]
