# Generated by Django 6.0.2 on 2026-03-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_add_bookmark_vacancyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='metro_city_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID города метро'),
        ),
    ]
