# Generated by Django 4.2.29 on 2026-04-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0020_add_metro_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('scam', 'Подозрение на мошенничество'), ('spam', 'Спам или реклама'), ('misleading', 'Некорректное описание вакансии'), ('suspicious_conditions', 'Подозрительные условия работы'), ('other', 'Другое')], max_length=64)),
                ('reason_text', models.TextField(blank=True)),
                ('self_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Обработано')], default='new', max_length=16)),
                ('moderator_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacancy_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_reports', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Жалоба на вакансию',
                'verbose_name_plural': 'Жалобы на вакансии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='vacancyreport',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='uniq_user_vacancy_report'),
        ),
    ]
