# Generated by Django 4.2.29 on 2026-04-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0022_vacancymoderationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_moderator_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ModeratorDeletionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина удаления')),
                ('vacancy_title', models.CharField(blank=True, max_length=255)),
                ('vacancy_company', models.CharField(blank=True, max_length=255)),
                ('vacancy_description', models.TextField(blank=True)),
                ('vacancy_external_id', models.CharField(blank=True, max_length=64)),
                ('manager_full_name', models.CharField(blank=True, max_length=255)),
                ('manager_email', models.CharField(blank=True, max_length=255)),
                ('moderator_full_name', models.CharField(blank=True, max_length=255)),
                ('moderator_email', models.CharField(blank=True, max_length=255)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('dominant_reason_code', models.CharField(blank=True, max_length=64)),
                ('dominant_reason_label', models.CharField(blank=True, max_length=128)),
                ('is_restored', models.BooleanField(db_index=True, default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Менеджер, создавший удалённую вакансию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_vacancy_reports', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_deletion_reports', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_vacancy_reports', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_deletions', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отчёт об удалении вакансии',
                'verbose_name_plural': 'Отчёты об удалении вакансий',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModeratorDeletionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vacancies.models._moderator_deletion_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vacancies.moderatordeletionreport')),
            ],
            options={
                'verbose_name': 'Фото-доказательство модератора',
                'verbose_name_plural': 'Фото-доказательства модератора',
                'ordering': ('order', 'id'),
            },
        ),
    ]
