# Generated by Django 4.2.29 on 2026-04-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0023_vacancy_is_moderator_deleted_alter_bookmark_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hharea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hhdictionaryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='moderator_note',
            field=models.TextField(blank=True, verbose_name='Заметка модератора'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='reason_code',
            field=models.CharField(choices=[('scam', 'Подозрение на мошенничество'), ('spam', 'Спам или реклама'), ('misleading', 'Некорректное описание вакансии'), ('suspicious_conditions', 'Подозрительные условия работы'), ('other', 'Другое')], max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='reason_text',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='self_status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Обработано')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='vacancyreport',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancyview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
